server:
  name: "evn_other"
  addr: "127.0.0.1:3458"
zap:
  # 日志文件路径
  debugFileName: ""
  infoFileName: ""
  warnFileName: ""
  # 日志文件大小
  maxSize: 500,
  # 日志文件保存时间
  maxAge: 28,
  # 日志文件最大备份数
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6376
  #  密码
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "other"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:12379"
mysql:
  #  数据库用户名
  username:
  #  数据库密码
  password:
  # 数据库地址
  host: 127.0.0.1
  # 数据库端口
  port: 3309
  # 数据库名称
  db: evn
jwt:
  #  过期时间 单位分钟
  accessExp: 60
  #  刷新时间 单位分钟
  refreshExp:
  #  加密密钥
  accessSecret:
  #   刷新密钥
  refreshSecret:
aes:
  # 用于加密用户ID的aes key 24位
  key: ""

host:
  tencentOss:
    # 腾讯云oss地址
    host: ""
  local:
    # 本地地址
    host: "http://127.0.0.1:8080"

live:
  #直播配置
  ip: "127.0.0.1"
  clientIP: "127.0.0.1"
  #端口配置
  rtmp: 1935
  flv: 7001
  hls: 7002
  api: 8090
  agreement: "http"
  cliAgreement: "http"
vod:
  # 腾讯云 云点播 appid
  appid:
  # 腾讯云 云点播 key
  key: ""
  # 腾讯云 腾讯云视立方 SDK  播放器 License URL
  licenseUrl: ""
  # 腾讯云 云点播 播放的音视频类型 RawAdaptive: 未加密的 转自适应码流 输出 Original: 上传 的原始音视频
  audioVideoType: "Original"
  # 腾讯云 云点播 允许输出的未加密的自适应码流模板 ID
  rawAdaptiveDefinition: 10
  # 腾讯云 云点播 pSing key 过期时间 (秒)
  psignExpire: 3600