server:
  name: "evn_api"
  addr: "127.0.0.1:8080"
  isHttps: false
  # 证书路径
  cert: ""
  # 私钥路径
  key: ""
zap:
  # 日志文件路径
  debugFileName: ""
  infoFileName: ""
  warnFileName: ""
  # 日志文件大小
  maxSize: 500,
  # 日志文件保存时间
  maxAge: 28,
  # 日志文件最大备份数
  MaxBackups: 3
grpc:
  addr: "127.0.0.1:8886"
  name: "api"
  version: "1.0.0"
  weight: 2
etcd:
  # etcd地址
  addrs:
    - "127.0.0.1:12379"
jwt:
  #  过期时间 单位分钟
  accessExp: 60
  #  刷新时间 单位分钟
  refreshExp:
  #  加密密钥
  accessSecret:
  #   刷新密钥
  refreshSecret:
host:
  tencentOss:
    # 腾讯云oss地址
    host: ""
  local:
    # 本地地址
    host: "http://127.0.0.1:8080"
upload:
  tencentOss:
    #地域  类似广州 ap-guangzhou
    region: ""
    #bucket 创建存储名称
    bucket: ""
    # 请填写您的SecretId
    secretId: ""
    # 请填写您的SecretKey
    secretKey: ""
    # 请填写您的存储桶的Appid
    appid: ""
    # host的格式为 https://eraser-go-live.oss-cn-hangzhou.aliyuncs.com 这中，请替换为您的真实信息。
    host: ""
    # Token有效期
    durationSeconds: 3600
    # 临时文件路径
    tmpFileUrl: ""
  local:
    # 文件保存路径
    fileUrl: ""
    # 临时文件路径
    tmpFileUrl: ""

