# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Download Packages
      run: cd ./server &&  go work sync
      
    - name: Build Api Server For Linux
      run: go build -v -o api ./evn_api/main.go

    - name: Build Other Server For Linux
      run: go build -v -o other ./evn_other/main.go
      
    - name: Build Api Server For Windows
      run: export CGO_ENABLED=0 GOOS=windows GOARCH=amd64 && go build -v -o api ./evn_api/main.go

    - name: Build Other Server For Windows
      run: export CGO_ENABLED=0 GOOS=windows GOARCH=amd64 && go build -v -o other ./evn_other/main.go
      
    - name: Upload Api Server
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ApiServer
        path: api.*
    - name: Upload Other Server
      uses: actions/upload-artifact@v3.1.2
      with:
        name: OtherServer
        path: other.*
        
